### PR TITLE
Increase setScriptTimeout

### LINKED ISSUE #14: ScriptTimeoutError
Hi,

It works well on a folder that contains a few HTML files but on a folder that that contains a lot of HTML files it doesn't work anymore.

```
ScriptTimeoutError: asynchronous script timeout: result was not received in 0.5 seconds
```

error

Maybe i'm wrong but I think this error comes from this line :
https://github.com/felixzapata/gulp-axe-webdriver/blob/2613bdb465e60f8a2c659995a66c358b591f3c8a/test/test.js#L23

Do you think it's possible to increase this value of 30000 ms ? or bypass it ? 

Thanks you,

### PR DESCRIPTION
**Pull request by okeul**
Fixes #14

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -29,7 +29,7 @@ module.exports = function (customOptions, done) {
 	var chromeOptions = options.headless ? { 'args': ['--headless'] } : {};
 	chromeCapabilities.set('chromeOptions', chromeOptions);
 	var driver = new WebDriver.Builder().withCapabilities(chromeCapabilities).build();
-	driver.manage().timeouts().setScriptTimeout(500);
+	driver.manage().timeouts().setScriptTimeout(60000);
```
Comment (ryuran) [inline index.js:32]: We should move this value to settings
